import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import GNB from "@/components/GNB";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}>
        <GNB />
        <main className="flex-1 min-h-screen">{children}</main>

        {/* 푸터: 아래로 밀착 (스크롤 고정 아님) */}
        <footer className="mt-auto">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
