type ProductSpec = {
  label: string;
  value: string;
};

export type Product = {
  slug: string;
  name: string;
  category: string;
  listImage: string;
  detailImage: string;
  summary: string;
  features: string[];
  specs: ProductSpec[];
  detailImages: string[];
};

export const products: Product[] = [
  {
    slug: "bicheong-mudmari-soap",
    name: "비청 머드마리비누",
    category: "비누",
    listImage: "/img/products/sample_shop_01.png",
    detailImage: "/img/products/detail_shop_01.png",
    summary: "비청 머드마리비누는 발모 및 피부재생 촉진용 광물질 조성물로 만들어진 최고급 벤토나이트성분이 함유된 특허받은 신비의 비누입니다.",
    features: ["쇼핑몰참고"],
    specs: [
      { label: "제품명", value: "비청머드마리" },
      { label: "내용량", value: "110g(건조시 약간의 차이가 있을수 있음)" },
      { label: "주성분", value: "초정수.스테아린산.미리스틸락.라우린산.산화강수.솔트액.발효수(가성소다)PG.구연산.피마자.국화추출물" },
      { label: "사용방법", value: "비누거품을 충분히 내어 2~3분간 부드럽게 맛사지한 후 물로 깨끗이 씻어냅니다." },
      { label: "소비자 상담번호", value: "1588-3705" },
    ],
    detailImages: ["/img/products/detail_shop_01_1.png"],
  },
  // {
  //   slug: "bicheong-new-mudmari-soap",
  //   name: "비청 뉴머드마리비누",
  //   category: "비누",
  //   listImage: "/img/products/sample_shop_02.gif",
  //   detailImage: "/img/products/detail_shop_02.png",
  //   summary: "뉴머드마리비누는 단순한 비누가 아니라,확실한 클렌징 효과는 물론! 신체체취방지,피부유연,경미한 피부질환에 도움을 주는 제품으로 피부질환에 보조요법을 하는 토탈 스킨케어 비누입니다.",
  //   features: [""],
  //   specs: [
  //     { label: "제품명", value: "뉴 머드마리 비청 비누" },
  //     { label: "내용량", value: "110g / (수분포함)" },
  //     { label: "전성분", value: "건조황산나트륨, 메타인산나트륨, 탄산수소나트륨" },
  //     { label: "소비자 상담번호", value: "1588-3705" },
  //     { label: "용판매가", value: "1셋트(비누4장)56,700원" },
  //   ],
  //   detailImages: ["/img/products/detail_shop_02_1.png"],
  // },
  // {
  //   slug: "bicheong-ariyul-bath",
  //   name: "비청 아리율 입욕제",
  //   category: "입욕제",
  //   listImage: "/img/products/sample_shop_03.gif",
  //   detailImage: "/img/products/detail_shop_03.png",
  //   summary:
  //     "천연 수정원석에서 수용성 실리카 (Neo Silica=gio3)를 수용성 크리스탈 에너지 실리카 결정체로 탄생시킨 수용성 규소로서 황산화효과인 이온수소가 방출되고,원적외선방출,향균,살균,부패방지와 피부세포활성화로 모세혈관을 확장시켜 혈액순환에 큰 도움을 줍니다.",
  //   features: ["수용성 규소", "피부 컨디션 케어", "편안한 사용감"],
  //   specs: [
  //     { label: "제품명", value: "비청 아리율 입욕제" },
  //     { label: "내용량", value: "30/g팩" },
  //     { label: "색상", value: "백색,무취,무독성" },
  //     { label: "제품사양 외형", value: "알루미늄 파우치" },
  //     { label: "성분", value: "규산염(sio3)규석(sio2)" },
  //     { label: "제조원", value: "한국에스캄(주)" },
  //     { label: "판매원", value: "(주)엘비씨" },
  //     { label: "유통기간", value: "제조일로부터 5년" },
  //     { label: "소비자 상담번호", value: "1588-3705" },
  //   ],
  //   detailImages: ["/img/products/detail_shop_03_1.png", "/img/products/detail_shop_03_2.png", "/img/products/detail_shop_03_3.png", "/img/products/detail_shop_03_4.png"],
  // },
  // {
  //   slug: "bicheong-ariyul-bath-500ml",
  //   name: "비청 아리율입욕제(500ml)",
  //   category: "입욕제",
  //   listImage: "/img/products/sample_shop_04.gif",
  //   detailImage: "/img/products/detail_shop_04.png",
  //   summary: "비청아리율 입욕제(액상)는 대장균,살모넬라균,녹농균,황색포도상구균 99.9%이상의 살균효과로 경미한 피부질환,발에무좀이 있으신분도 사용하시면 많은 도움이됩니다.",
  //   features: [
  //     "온수에 녹이면 천연 미네랄 온천수처럼 사용 가능",
  //     "전신욕·반신욕 시 마사지 병행 시 효과 강화",
  //     "씻어내지 않아도 되는 간편 사용",
  //     "살균·세정 효과로 세탁·타일 청소 활용 가능",
  //     "식물 성장 도움 및 병충해 예방",
  //     "개봉 후 냉장 보관 시 탈취 효과",
  //   ],
  //   specs: [
  //     { label: "제품명", value: "비청 아리율 입욕제(액상)" },
  //     { label: "내용량", value: "500ml" },
  //     { label: "성분", value: "규산염(sio3)규석(sio2)" },
  //     { label: "제조원", value: "한국에스캄(주)" },
  //     { label: "판매원", value: "(주)엘비씨" },
  //     { label: "유통기간", value: "제조일로부터 5년" },
  //     { label: "소비자 상담번호", value: "1588-3705" },
  //   ],
  //   detailImages: ["/img/products/detail_shop_04_1.png", "/img/products/detail_shop_04_2.png", "/img/products/detail_shop_04_3.png", "/img/products/detail_shop_04_4.png"],
  // },
  // {
  //   slug: "mijin-cleanser-2pack",
  //   name: "美人 청결제(2장)",
  //   category: "청결제",
  //   listImage: "/img/products/sample_shop_05.gif",
  //   detailImage: "/img/products/detail_shop_05.png",
  //   summary: "미인 청결제는 알카리 성분으로 원적외선 및 자정능력이 함유된 천연광물을 기본원료로 물성분을 부드럽게하고 피부보호에 효능있는 무공해물질입니다.(미네랄 함유)",
  //   features: [
  //     "천연 광물 기반 청결 케어",
  //     "미네랄 함유로 순한 사용감",
  //     "피부를 산뜻하게 세정",
  //     "불쾌한 냄새 관리에 도움",
  //     "다양한 부위에 활용 가능",
  //     "항균 세정으로 위생 관리",
  //     "일상 사용에 적합한 순한 성분",
  //   ],
  //   specs: [
  //     { label: "주성분", value: "복합 규산나트륨" },
  //     { label: "색상", value: "백색" },
  //     { label: "소비자가격", value: "15,000원(1set/2개)" },
  //     { label: "제조원", value: "한국에스캄(주)" },
  //     { label: "판매원", value: "(주)엘비씨" },
  //     { label: "소비자 상담번호", value: "1588-3705" },
  //   ],
  //   detailImages: ["/img/products/detail_shop_05_1.png", "/img/products/detail_shop_05_2.png"],
  // },
  // {
  //   slug: "mijin-cleanser-single",
  //   name: "美人 청결제 (낱개)",
  //   category: "청결제",
  //   listImage: "/img/products/sample_shop_05.gif",
  //   detailImage: "/img/products/detail_shop_05.png",
  //   summary: "미인 청결제는 알카리 성분으로 원적외선 및 자정능력이 함유된 천연광물을 기본원료로 물성분을 부드럽게하고 피부보호에 효능있는 무공해물질입니다.(미네랄 함유)",
  //   features: [
  //     "천연 광물 기반 청결 케어",
  //     "미네랄 함유로 순한 사용감",
  //     "피부를 산뜻하게 세정",
  //     "불쾌한 냄새 관리에 도움",
  //     "다양한 부위에 활용 가능",
  //     "항균 세정으로 위생 관리",
  //     "일상 사용에 적합한 순한 성분",
  //   ],
  //   specs: [
  //     { label: "주성분", value: "복합 규산나트륨" },
  //     { label: "색상", value: "백색" },
  //     { label: "소비자가격", value: "5,000원 1set/1개(낱개)" },
  //     { label: "제조원", value: "한국에스캄(주)" },
  //     { label: "판매원", value: "(주)엘비씨" },
  //     { label: "소비자 상담번호", value: "1588-3705" },
  //   ],
  //   detailImages: ["/img/products/detail_shop_06_1.png", "/img/products/detail_shop_05_2.png"],
  // },

  // 수처리제 제품!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  {
    slug: "bicheong-waterclean-a",
    name: "비청 씨크린 10L (해수용)",
    category: "수처리제",
    listImage: "/img/products/water_01.png",
    detailImage: "/img/products/detail_water_01.gif",
    summary:
      "비청씨크린은 규석을 특수제법으로 정제하여 추출한 복합수용성규산염으로, 적조 및 녹조 발생 원인인 독성 플랑크톤 코클로디니움을 억제하며, 22종 이상의 다양한 천연 미네랄을 풍부하게 함유하고 있는 무독성의 제품입니다.",
    features: [
      "먹는 물 관리법 제18조 제2항 규정에 의한 성분",
      "산화 이온 환원성 물질",
      "치환력 증가",
      "살균효과",
      " 물,공기권 개선",
      "P(인)함유물질의 전이(SiㅡOㅡSi ⇄ SiㅡOㅡP)",
      "수표면적확대: H2O, P, K, Ai 중금속 흡수",
      "항 곰팡이,항균,항산화작용으로 면역력증가(사료 찌꺼기 등 변패방지)",
      "유익 미생물의 활성도를 높여 장내유익 미생물 균총 정상화",
      "항 스트레스 작용으로 어류의 활력증가",
    ],
    specs: [
      { label: "제품명", value: "비청 씨크린" },
      { label: "분류", value: "복합수용성 규산염" },
      { label: "등록번호", value: "충남 천안 86-가-10404호" },
      { label: "성분", value: "Na2Sio3-10H2O.NaCo3.기타" },
      { label: "외형", value: "액상" },
      { label: "용도", value: "수처리제" },
      { label: "용량", value: "10L" },
      { label: "포장", value: "플라스틱 용기" },
      { label: "유통기한", value: "2년" },
      { label: "소비자 상담번호", value: "1588-3705" },
      { label: "판매가", value: "180,000원" },
      { label: "제품 사용 시 보관사항", value: "물기 및 습기에 닿지 않는 신선한 곳에 보관" },
      { label: "특이사항", value: "본 제품(Na2SiO3-10H20)은 수용성 물질로 즉효성 물질임. 제품 사용시 인축에 피해가 없으며 피부에 묻으면 물로 씻는다." },
    ],
    detailImages: [
      "/img/products/detail_water_01_1.gif",
      "/img/products/detail_water_01_2.jpg",
      "/img/products/detail_water_01_33.png",
      "/img/products/detail_water_01_4.png",
      "/img/products/detail_water_01_5.png",
      "/img/products/detail_water_01_6.png",
    ],
  },
  // {
  //   slug: "bicheong-waterclean-b",
  //   name: "비청 씨크린 20L (민물용)",
  //   category: "수처리제",
  //   listImage: "/img/products/water_02.png",
  //   detailImage: "/img/products/detail_water_02.png",
  //   summary: "비청씨크린(민물용)은 4-5기가의 산소를 발생시켜 미생물을 억제시키며, 낚시터, 강, 호수, 저수지, 양식장 등의 민물에 사용하는 무독성의 제품입니다.",
  //   features: [
  //     "먹는 물 관리법 제18조 제2항 규정에 의한 성분",
  //     "산화 이온 환원성 물질",
  //     "치환력 증가",
  //     "살균효과",
  //     " 물,공기권 개선",
  //     "P(인)함유물질의 전이(SiㅡOㅡSi ⇄ SiㅡOㅡP)",
  //     "수표면적확대: H2O, P, K, Ai 중금속 흡수",
  //     "항 곰팡이,항균,항산화작용으로 면역력증가(사료 찌꺼기 등 변패방지)",
  //     "유익 미생물의 활성도를 높여 장내유익 미생물 균총 정상화",
  //     "항 스트레스 작용으로 어류의 활력증가",
  //   ],
  //   specs: [
  //     { label: "제품명", value: "비청 씨크린" },
  //     { label: "분류", value: "복합수용성 규산염" },
  //     { label: "등록번호", value: "충남 천안 86-가-10404호" },
  //     { label: "성분", value: "Na2Sio3-10H2O.NaCo3.기타" },
  //     { label: "외형", value: "액상" },
  //     { label: "용도", value: "수처리제" },
  //     { label: "용량", value: "10L" },
  //     { label: "포장", value: "플라스틱 용기" },
  //     { label: "유통기한", value: "2년" },
  //     { label: "소비자 상담번호", value: "1588-3705" },
  //     { label: "판매가", value: "180,000원" },
  //     { label: "제품 사용 시 보관사항", value: "물기 및 습기에 닿지 않는 신선한 곳에 보관" },
  //     { label: "특이사항", value: "본 제품(Na2SiO3-10H20)은 수용성 물질로 즉효성 물질임. 제품 사용시 인축에 피해가 없으며 피부에 묻으면 물로 씻는다." },
  //   ],
  //   detailImages: [
  //     "/img/products/detail_water_02_1.png",
  //     "/img/products/detail_water_01_33.png",
  //     "/img/products/detail_water_01_4.png",
  //     "/img/products/detail_water_01_5.png",
  //     "/img/products/detail_water_01_6.png",
  //   ],
  // },
  {
    slug: "bicheong-water-powder",
    name: "비청 수처리 파우더",
    category: "수처리제",
    listImage: "/img/products/water_03.png",
    detailImage: "/img/products/detail_water_03.png",
    summary: "분말 타입으로 보관이 쉬운 수처리 전용 파우더입니다.",
    features: [
      "먹는 물 관리법 제18조 제2항 규정에 의한 성분",
      "산화 이온 환원성 물질",
      "치환력 증가",
      "살균효과",
      " 물,공기권 개선",
      "P(인)함유물질의 전이(SiㅡOㅡSi ⇄ SiㅡOㅡP)",
      "수표면적확대: H2O, P, K, Ai 중금속 흡수",
      "항 곰팡이,항균,항산화작용으로 면역력증가(사료 찌꺼기 등 변패방지)",
      "유익 미생물의 활성도를 높여 장내유익 미생물 균총 정상화",
      "항 스트레스 작용으로 어류의 활력증가",
    ],
    specs: [
      { label: "제품명", value: "비청 씨크린" },
      { label: "분류", value: "복합수용성 규산염" },
      { label: "등록번호", value: "충남 천안 86-가-10404호" },
      { label: "성분", value: "Na2Sio3-10H2O.NaCo3.기타" },
      { label: "외형", value: "액상" },
      { label: "용도", value: "수족관용 수처리제" },
      { label: "용량", value: "500ml" },
      { label: "포장", value: "플라스틱 용기" },
      { label: "유통기한", value: "3년" },
      { label: "소비자 상담번호", value: "1588-3705" },
      { label: "판매가", value: "20,000원" },
      { label: "제품 사용 시 보관사항", value: "물기 및 습기에 닿지 않는 신선한 곳에 보관" },
      { label: "특이사항", value: "수용성 물질로 즉효성 물질임. 제품 사용시 인축에 피해가 없으며 피부에 묻으면 물로 씻는다." },
    ],
    detailImages: ["/img/products/detail_water_01_33.png", "/img/products/detail_water_01_4.png", "/img/products/detail_water_01_5.png", "/img/products/detail_water_01_6.png"],
  },
  {
    slug: "bicheong-water-powder",
    name: "비청 수처리 파우더",
    category: "수처리제",
    listImage: "/img/products/water_04.png",
    detailImage: "/img/products/detail_water_044.png",
    summary: "분말 타입으로 보관이 쉬운 수처리 전용 파우더입니다.",
    features: ["분말 타입", "보관 용이", "물때 감소"],
    specs: [
      { label: "중량", value: "300g" },
      { label: "사용 목적", value: "수질 정화" },
      { label: "사용 방법", value: "물에 희석" },
      { label: "권장 사용", value: "주 1~2회" },
    ],
    detailImages: ["/img/products/detail_water_03_1.gif", "/img/products/detail_water_03_2.gif"],
  },

  // 농자제 제품@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  {
    slug: "agri-growth-a",
    name: "비청 플러스",
    category: "농자제",
    listImage: "/img/products/B_01.png",
    detailImage: "/img/products/B_01.png",
    summary: "모든 농작물에 폭넓게 적용 가능한 엽면시비용 농자제입니다.",
    features: ["적용 작물: 수도작, 전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등", "희석 배수: 500배, 1,000배, 1,500배", "7~10일 간격 정기 살포 권장"],
    specs: [
      { label: "용량", value: "1L" },
      { label: "적용 작물", value: "수도작, 전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등 모든 농작물" },
      { label: "희석 배수", value: "500배, 1,000배, 1,500배액 살포" },
      { label: "사용시기(회본과)", value: "육묘기 3회, 분포 2회(수잉기 출수 직전)" },
      { label: "사용시기(과수)", value: "개화 전, 꽃 진 후, 적과 후 각 1회" },
      { label: "추가 살포", value: "1회 살포 후 7~10일 간격으로 수확 시까지 살포" },
      { label: "사용방법", value: "엽면 시비, 7~10일 간격 살포" },
      { label: "보관", value: "직사광선을 피한 실온 보관" },
    ],
    detailImages: ["/img/products/detail_B_01_01.png"],
  },
  {
    slug: "agri-growth-b",
    name: "비청 실로암",
    category: "농자제",
    listImage: "/img/products/B_02.png",
    detailImage: "/img/products/B_02.png",
    summary: "전작부터 과수까지 폭넓게 적용 가능한 살포/관주용 농자제입니다.",
    features: ["적용 작물: 전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등", "사용량: 500배, 1,000배액 살포", "5일 간격 정기 살포 및 관주 권장"],
    specs: [
      { label: "용량", value: "2L" },
      { label: "적용 작물", value: "전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등 모든 농작물" },
      { label: "사용량", value: "500배, 1,000배액으로 살포" },
      { label: "초기 사용량", value: "600L/1L" },
      { label: "중기 사용량", value: "500L/1L" },
      { label: "사용시기(화본과)", value: "육묘기 3회, 분포 3회" },
      { label: "사용시기(과수)", value: "개화 전, 꽃 진 후 각 1회 살포" },
      { label: "추가 사용", value: "5일 간격으로 수확 시까지 살포 및 관주" },
      { label: "사용방법", value: "엽면 살포 및 관주 병행" },
    ],
    detailImages: ["/img/products/detail_B_02_01.png"],
  },
  {
    slug: "agri-growth-c",
    name: "농자제 감마",
    category: "농자제",
    listImage: "/img/products/B_03.png",
    detailImage: "/img/products/B_03.png",
    summary: "전작부터 과수까지 적용 가능한 살포/관주용 농자제입니다.",
    features: ["적용 작물: 전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등", "사용량: 500배, 1,000배, 1,500배액 살포", "5일 간격 정기 살포 및 관주 권장"],
    specs: [
      { label: "용량", value: "1L" },
      { label: "적용 작물", value: "전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등 모든 농작물" },
      { label: "사용량", value: "500배, 1,000배, 1,500배액으로 살포" },
      { label: "초기 사용량", value: "600L/1L" },
      { label: "중기 사용량", value: "500L/1L" },
      { label: "사용시기(화본과)", value: "육묘기 3회, 분포 3회" },
      { label: "사용시기(과수)", value: "개화 전, 꽃 진 후 각 1회 살포" },
      { label: "추가 사용", value: "5일 간격으로 수확 시까지 살포 및 관주" },
      { label: "사용방법", value: "엽면 살포 및 관주 병행" },
    ],
    detailImages: ["/img/products/detail_B_03_01.png"],
  },
  {
    slug: "agri-growth-d",
    name: "농자제 델타",
    category: "농자제",
    listImage: "/img/products/B_04.png",
    detailImage: "/img/products/B_04.png",
    summary: "전작부터 과수까지 적용 가능한 엽면시비/관주용 농자제입니다.",
    features: ["적용 작물: 전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등", "엽면시비 500배액 살포 (물 500L/1L)", "관주: 150~200평 기준 1L~2L 사용"],
    specs: [
      { label: "용량", value: "1L" },
      { label: "적용 작물", value: "전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등 모든 농작물" },
      { label: "사용량(엽면시비)", value: "500배액으로 살포 (물 500L/1L)" },
      { label: "사용량(관주)", value: "150~200평 기준 1L~2L" },
      { label: "사용시기", value: "과수 개화시부터 꽃 진 후 살포" },
      { label: "추가 사용", value: "5일 간격으로 수확 시까지 살포 및 관주" },
      { label: "사용방법", value: "엽면시비 및 관주 병행" },
    ],
    detailImages: ["/img/products/detail_B_04_01.png"],
  },
  {
    slug: "agri-growth-e",
    name: "농자제 엡실론",
    category: "농자제",
    listImage: "/img/products/B_05.png",
    detailImage: "/img/products/B_05.png",
    summary: "토양개선과 과실품질 관리에 활용 가능한 엽면시비/관주용 농자제입니다.",
    features: ["적용 작물: 전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등", "효과: 토양개선, 과실품질, 염류해소, pH 조절", "화본과/과수 모두 생육 단계별 수시 사용 가능"],
    specs: [
      { label: "용량", value: "1L" },
      { label: "적용 작물", value: "전작, 원예(노지/시설), 과수, 특작, 화훼, 약초 등 모든 농작물" },
      { label: "효과", value: "토양개선, 과실품질 향상, 염류해소, pH 조절" },
      { label: "사용시기(화본과)", value: "육묘기부터 수시 사용" },
      { label: "사용시기(과수)", value: "개화 전부터 수시 사용" },
      { label: "사용방법(엽면 시비)", value: "500L(25말)/1L" },
      { label: "사용방법(관주)", value: "150~200평/1L" },
    ],
    detailImages: ["/img/products/detail_B_05_01.png"],
  },
];
